In [11]:
from keras.models import load_model

model = load_model('D:/OneDrive/Major Project/HybridModel_37Classes/params/00006-test-train/model-29-0.15.hdf5')

In [12]:
from keras.preprocessing.image import ImageDataGenerator

test_datagenerator = ImageDataGenerator(rescale=1/255)

test_generator = test_datagenerator.flow_from_directory(
    directory="../Data/GalaxyZoo1/test1/",
    classes=['images_test_rev1'],
    class_mode=None,
    color_mode="rgb",
    batch_size=1,
    target_size=(299, 299),
    seed=123,
    shuffle=False)

Found 1 images belonging to 1 classes.


In [13]:
predictions = model.predict(
    test_generator,
    steps=test_generator.n/test_generator.batch_size,
    verbose=1)

1/1 [==============================] - 6s 6s/step


In [14]:
predictions

array([[2.3950830e-05, 4.8960963e-01, 2.8947727e-12, 5.7384488e-12,
        2.1398950e-01, 3.3590138e-12, 2.0845260e-02, 2.6302585e-01,
        6.3896907e-04, 2.9497715e-13, 2.4975511e-11, 3.3255963e-12,
        2.5095546e-12, 5.1021591e-12, 5.2516568e-03, 3.3821058e-12,
        3.9217859e-03, 2.0310106e-03, 5.0403037e-12, 3.9226061e-13,
        9.0119963e-13, 2.1892356e-12, 4.5795078e-12, 1.5604396e-12,
        6.1410933e-12, 6.6240289e-04, 2.3912790e-12, 7.2339886e-12,
        6.9699814e-12, 4.2568462e-12, 7.2983600e-13, 4.7401137e-12,
        1.0164457e-12, 1.6060995e-12, 3.6224120e-12, 4.2624684e-12,
        3.0618427e-12]], dtype=float32)

In [15]:
prediciton = predictions.flatten()

In [16]:
prediciton

array([2.3950830e-05, 4.8960963e-01, 2.8947727e-12, 5.7384488e-12,
       2.1398950e-01, 3.3590138e-12, 2.0845260e-02, 2.6302585e-01,
       6.3896907e-04, 2.9497715e-13, 2.4975511e-11, 3.3255963e-12,
       2.5095546e-12, 5.1021591e-12, 5.2516568e-03, 3.3821058e-12,
       3.9217859e-03, 2.0310106e-03, 5.0403037e-12, 3.9226061e-13,
       9.0119963e-13, 2.1892356e-12, 4.5795078e-12, 1.5604396e-12,
       6.1410933e-12, 6.6240289e-04, 2.3912790e-12, 7.2339886e-12,
       6.9699814e-12, 4.2568462e-12, 7.2983600e-13, 4.7401137e-12,
       1.0164457e-12, 1.6060995e-12, 3.6224120e-12, 4.2624684e-12,
       3.0618427e-12], dtype=float32)

In [7]:
import numpy as np

In [8]:
print(np.where(prediciton==max(prediciton)))

(array([14], dtype=int64),)


In [9]:
classes = [
    'Class1.1', 'Class1.2', 'Class1.3', 'Class2.1', 'Class2.2', 'Class3.1',
    'Class3.2', 'Class4.1', 'Class4.2', 'Class5.1', 'Class5.2', 'Class5.3',
    'Class5.4', 'Class6.1', 'Class6.2', 'Class7.1', 'Class7.2', 'Class7.3',
    'Class8.1', 'Class8.2', 'Class8.3', 'Class8.4', 'Class8.5', 'Class8.6',
    'Class8.7', 'Class9.1', 'Class9.2', 'Class9.3', 'Class10.1', 'Class10.2',
    'Class10.3', 'Class11.1', 'Class11.2', 'Class11.3', 'Class11.4',
    'Class11.5', 'Class11.6'
]